/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.9-dev at Wed Jul 30 16:14:59 2014. */

#ifndef _PB_SETTINGS_PB_H_
#define _PB_SETTINGS_PB_H_
#include "pb.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _POSTConfig {
    size_t ip_count;
    uint32_t ip[8];
    uint32_t port;
    uint64_t interval;
    bool has_offset;
    uint64_t offset;
} POSTConfig;

typedef struct _SensorConfig {
    bool hasADC1;
    bool hasADC2;
    bool hasRain;
    size_t avrIDs_count;
    uint32_t avrIDs[8];
    uint64_t interval;
} SensorConfig;

/* Default values for struct fields */

/* Field tags (for use in manual encoding/decoding) */
#define POSTConfig_ip_tag                        1
#define POSTConfig_port_tag                      2
#define POSTConfig_interval_tag                  3
#define POSTConfig_offset_tag                    4
#define SensorConfig_hasADC1_tag                 1
#define SensorConfig_hasADC2_tag                 2
#define SensorConfig_hasRain_tag                 3
#define SensorConfig_avrIDs_tag                  4
#define SensorConfig_interval_tag                5

/* Struct field encoding specification for nanopb */
extern const pb_field_t SensorConfig_fields[6];
extern const pb_field_t POSTConfig_fields[5];

/* Maximum encoded size of messages (where known) */
#define SensorConfig_size                        65
#define POSTConfig_size                          76

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
