/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.9-dev at Wed Jul 30 16:14:59 2014. */

#include "settings.pb.h"



const pb_field_t SensorConfig_fields[6] = {
    PB_FIELD2(  1, BOOL    , REQUIRED, STATIC  , FIRST, SensorConfig, hasADC1, hasADC1, 0),
    PB_FIELD2(  2, BOOL    , REQUIRED, STATIC  , OTHER, SensorConfig, hasADC2, hasADC1, 0),
    PB_FIELD2(  3, BOOL    , REQUIRED, STATIC  , OTHER, SensorConfig, hasRain, hasADC2, 0),
    PB_FIELD2(  4, UINT32  , REPEATED, STATIC  , OTHER, SensorConfig, avrIDs, hasRain, 0),
    PB_FIELD2(  5, UINT64  , REQUIRED, STATIC  , OTHER, SensorConfig, interval, avrIDs, 0),
    PB_LAST_FIELD
};

const pb_field_t POSTConfig_fields[5] = {
    PB_FIELD2(  1, UINT32  , REPEATED, STATIC  , FIRST, POSTConfig, ip, ip, 0),
    PB_FIELD2(  2, UINT32  , REQUIRED, STATIC  , OTHER, POSTConfig, port, ip, 0),
    PB_FIELD2(  3, UINT64  , REQUIRED, STATIC  , OTHER, POSTConfig, interval, port, 0),
    PB_FIELD2(  4, UINT64  , OPTIONAL, STATIC  , OTHER, POSTConfig, offset, interval, 0),
    PB_LAST_FIELD
};


