/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.9-dev at Tue Jul  8 09:47:02 2014. */

#ifndef _PB_MESSAGE_PB_H_
#define _PB_MESSAGE_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _Example {
    int32_t value;
} Example;

/* Default values for struct fields */

/* Field tags (for use in manual encoding/decoding) */
#define Example_value_tag                        1

/* Struct field encoding specification for nanopb */
extern const pb_field_t Example_fields[2];

/* Maximum encoded size of messages (where known) */
#define Example_size                             11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
