/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.9-dev at Tue Jul  8 09:47:02 2014. */

#include "message.pb.h"



const pb_field_t Example_fields[2] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC  , FIRST, Example, value, value, 0),
    PB_LAST_FIELD
};


