MKL25ZRF =  



CONTIKI_TARGET_DIRS = . dev apps net

CLEAN += symbols.c symbols.h *.frdm-kl25z-rf

# Master clock frequency
MCK = 48000000

CONTIKI_TARGET_MAIN = contiki-main.c 

ARCH = cc1120-config.c cc1120.c cc1120-arch-frdm-kl25z-rf.c\
		leds-arch.c

CONTIKI_TARGET_SOURCEFILES += contiki-main.c
CONTIKI_TARGET_SOURCEFILES += $(ARCH)

include $(CONTIKI)/cpu/arm/mkl25z/Makefile.mkl25z

ifndef BASE_IP
BASE_IP := 172.16.1.1
endif

